# v2 syntax
version: '2'

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:10.3-alpine
    restart: always
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_PASSWORD: iugo
      POSTGRES_USER: iugo
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
