# v2 syntax
version: '2'

volumes:
  postgres-data:
    driver: local

services:
  # postgres:
  #   image: postgres:10.3-alpine
  #   restart: always
  #   command: postgres -c 'max_connections=500'
  #   environment:
  #     POSTGRES_DB: pgdb
  #     POSTGRES_PASSWORD: iugo
  #     POSTGRES_USER: iugo
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: iugo
      MONGO_INITDB_ROOT_PASSWORD: iugo
    ports:
      - "27017:27017"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
